// This file was generated by the AutoAPI tool. Do not modify.
import io.ktor.client.HttpClient
import io.ktor.client.features.json.JsonFeature
import io.ktor.client.request.`get`
import io.ktor.client.request.post
import kotlin.Int
import kotlin.String
import kotlin.js.JsExport
import kotlin.js.Promise
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.promise

@JsExport
public class AutoAPI(
  private val basePath: String = ""
) {
  private val client: HttpClient = HttpClient { install (JsonFeature) }

  public fun getListing(name: String, page: Int): Promise<SampleResponse> {
    val location = "$basePath/list/$name/page/$page"
    return GlobalScope.promise { client.`get`(location) }
  }

  public fun postListing(name: String, page: Int): Promise<SampleResponse> {
    val location = "$basePath/list/$name/page/$page"
    return GlobalScope.promise { client.post(location) }
  }
}
