// This file was generated by the AutoAPI tool. Do not modify.
import io.ktor.client.*
import io.ktor.client.features.json.*
import io.ktor.client.request.*
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.promise
import kotlin.js.Promise

@JsExport
public class AutoAPI(
  private val basePath: String = ""
) {
  private val client: HttpClient = HttpClient { install (JsonFeature) }

  public fun getRestaurants(): Promise<Map<String, Restaurant>> {
    val location = "$basePath/restaurants"
    return GlobalScope.promise { client.`get`(location) }
  }

  public fun getRestaurant(id: Int): Promise<Restaurant> {
    val location = "$basePath/restaurants/$id"
    return GlobalScope.promise { client.`get`(location) }
  }

  public fun createRestaurant(body: NewRestaurant): Promise<Restaurant> {
    val location = "$basePath/restaurants"
    return GlobalScope.promise { client.post(location) { this.body = body } }
  }
}
