// This file was generated by the AutoAPI tool. Do not modify.
import com.malcolmcrum.autoapi.client.Map
import io.ktor.client.*
import io.ktor.client.features.json.*
import io.ktor.client.request.*
import io.ktor.http.*
import io.ktor.http.ContentType.Application.Json
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.promise
import kotlin.js.Promise

@JsExport
public class AutoAPI(
  private val basePath: String = ""
) {
  private val client: HttpClient = HttpClient { install (JsonFeature) }

  public fun getRestaurants(): Promise<Array<Restaurant>> {
    val location = "$basePath/restaurants"
    return GlobalScope.promise { client.`get`(location) }
  }

  public fun getRestaurantMap(): Promise<Map<Int, Restaurant>> {
    val location = "$basePath/restaurants/map"
    return GlobalScope.promise { client.`get`(location) }
  }

  public fun getRestaurant(id: Int): Promise<Restaurant> {
    val location = "$basePath/restaurants/$id"
    return GlobalScope.promise { client.`get`(location) }
  }

  public fun createRestaurant(body: NewRestaurant): Promise<Restaurant> {
    val location = "$basePath/restaurants"
    return GlobalScope.promise { client.post(location) { contentType(Json); this.body = body } }
  }
}
